global:
  scrape_interval: 10s # Set the scraping interval

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:9249', 'flink-taskmanager:9250']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:7000']
