# Dockerfile.edge
FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    libopencv-dev \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install \
    kafka-python \
    ultralytics \
    opencv-python

# Copy code
COPY edge_detector.py /app/edge_detector.py
COPY mlmodel.onnx /app/mlmodel.onnx

# Set working directory
WORKDIR /app

# Run the detector
CMD ["python", "edge_detector.py"]