version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  edge-detector:
    build: ./edge-detector
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - /dev/video0:/dev/video0  # Pass through camera
    network_mode: host  # Use host network for camera access

  flink-jobmanager:
    image: flink:1.17-scala_2.12
    build: ./flink-job
    depends_on:
      - kafka
    ports:
      - "8081:8081"  # Flink dashboard
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    command: jobmanager

  flink-taskmanager:
    image: flink:1.17-scala_2.12
    depends_on:
      - flink-jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    command: taskmanager